### ISSUE TITLE
Implement I/O using UART.

### ISSUE THREAD

**Issue by ll-KS-ll** [ll-KS-ll/tsea83-aktakurvan#7]
Create a module for I/O using UART for our computer.

Some examples/demonstration projects for Nexys3 are available here: 
http://www.digilentinc.com/Products/Detail.cfm?NavPath=2,400,897&Prod=NEXYS3
UART seems to be used in at least one of them.

**Comment by ljukas** [comment]
Uart controller is finished. Now all that needs to be done is to make the cpu able to take an interupt and read it.

**Comment by ljukas** [comment]
Easiest way to test it is to use the leddriver component from the Uart lab.

**Comment by ljukas** [comment]
Tested. Works as it should. Needs to be implemented with CPU then it's done.
